common: &default_settings
  canvas_url: <%= ENV['CANVAS_URL'] %>
  canvas_token: <%= ENV['CANVAS_TOKEN'] %>

development:
  <<: *default_settings

production:
  <<: *default_settings

test:
  <<: *default_settings

staging:
  <<: *default_settings
